---
# Installs Consul agent

- name: Ensure required utilities are present
  apt:
    name:
      - curl
      - gnupg2
    state: latest
    update_cache: yes
  become: true

- name: Import Hashicorp GPG key
  shell:
    cmd: "curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/hashicorp-archive-keyring.gpg --import"
    creates: "/etc/apt/trusted.gpg.d/hashicorp-archive-keyring.gpg"
    warn: False
  register: gpg_key_import_output
  become: true

- name: Fix GPG key permissions
  file:
    path: "/etc/apt/trusted.gpg.d/hashicorp-archive-keyring.gpg"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  become: true
  when: gpg_key_import_output.changed

- name: Add Hashicorp APT repository
  copy:
    content: >-
      deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main
    dest: /etc/apt/sources.list.d/hashicorp.list
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  become: true
  when: gpg_key_import_output.changed

- name: Install latest version of Consul
  apt: name=consul state=latest update_cache=yes
  become: true

- name: Copy agent configuration
  template:
    src: "templates/agent.hcl.j2"
    dest: /etc/consul.d/consul.hcl
    owner: consul
    group: consul
    mode: 0644
  become: true
  notify:
    - Restart Consul

- name: Copy server configuration
  template:
    src: "templates/server.hcl.j2"
    dest: /etc/consul.d/server.hcl
    owner: consul
    group: consul
    mode: 0644
  become: true
  when: consul_agent_type == 'server'
  notify:
    - Restart Consul

- name: Ensure TLS certificate directory exists
  file:
    path: /etc/consul.d/tls
    state: directory
    owner: "consul"
    group: "consul"
    mode: 0740
  become: true
  when: consul_agent_cert_file and consul_agent_key_file

- name: Start Consul
  systemd: name=consul enabled=yes state=started daemon_reload=true
  become: true
