---
# Configures ACLs

- name: Create agent policy
  consul_acl_policy:
    name: "{{ ansible_hostname }}"
    rules: |
      # Allow the agent to register its own node in the Catalog and update its network coordinates
      node "{{ ansible_hostname }}" {
        policy = "write"
      }
      # Allows the agent to detect and diff services registered to itself with what is known in the Catalog
      node_prefix "" {
        policy = "read"
      }
      service_prefix "" {
        policy = "read"
      }
      # Allow agent to manage itself
      agent "{{ ansible_hostname }}" {
        policy = "write"
      }
    datacenters:
      - "{{ consul_datacenter }}"
    state: present
    mgmt_token: "{{ consul_acl_initial_management_token }}"
  register: consul_acl_agent_policy_output

- name: Create agent token
  consul_acl_token:
    secret_id: "{{ consul_acl_agent_token }}"
    description: "{{ ansible_hostname }} agent token"
    policies:
      - id: "{{ consul_acl_agent_policy_output.policy.id }}"
    local: true
    state: present
    mgmt_token: "{{ consul_acl_initial_management_token }}"
  register: consul_acl_agent_token_output

- set_fact:
    consul_acl_agent_token: "{{ consul_acl_agent_token_output.token.secret_id }}"

- block:
    - name: Create a policy to allow DNS queries and service lookups
      consul_acl_policy:
        name: "dns-requests"
        rules: |
          node_prefix "" {
            policy = "read"
          }
          service_prefix "" {
            policy = "read"
          }
        state: present
        mgmt_token: "{{ consul_acl_initial_management_token }}"
      register: consul_acl_dns_policy_output

    - name: Assign dns request policy to default token
      consul_acl_token:
        secret_id: "{{ consul_acl_token_default }}"
        description: "Token for DNS requests"
        policies:
          - id: "{{ consul_acl_dns_policy_output.policy.id }}"
        state: present
        mgmt_token: "{{ consul_acl_initial_management_token }}"
      register: consul_acl_token_default_output
      when: consul_acl_token_default

    - name: Create an anonymous token
      consul_acl_token:
        secret_id: anonymous
        description: "Anonymous Token"
        policies:
          - id: "{{ consul_acl_dns_policy_output.policy.id }}"
        state: present
        mgmt_token: "{{ consul_acl_initial_management_token }}"
      register: consul_acl_token_default_output
      when: not consul_acl_token_default

    - set_fact:
        consul_acl_token_default: "{{ consul_acl_token_default_output.token.secret_id }}"

  run_once: true

- name: Copy agent configuration
  template:
    src: "templates/agent.hcl.j2"
    dest: /etc/consul.d/consul.hcl
    owner: consul
    group: consul
    mode: 0644
  become: true
  notify:
    - Restart Consul
